# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Rajesh
tagline:          'Creativity Leads To Innovation'
description:      ''
url:              http://www.rajeshrram.com
baseurl:          /

author:
  name:           'Rajeshkumar Ramasamy'
  url:            https://twitter.com/rajeshrram

paginate:         1

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/rajeshrram
