# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Rajeshkumar
tagline:          'Creativity Leads To Innovation'
description:      ''
url:              http://www.rajeshrram.com
baseurl:          /

author:
  name:           'Rajeshkumar Ramasamy'
  url:            https://twitter.com/rajeshrram

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/rajeshrram

 
 # This is the list of pages to incldue in the header of the website.
pages_list:       {'About':'/about','Archive':'/archive','Feed':'/atom.xml'}