# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Rajeshkumar 
tagline:             'Software Developer in Bangalore'
description:         'Creativity Leads To Innovation'
url:                 http://www.rajeshrram.com
giturl:				 http://rajeshrram.github.io
baseurl:             /
paginate:            5
rss:                 atom.xml

# About/contact
author:
  name:             Rajeshkumar R
  github:           rajeshrram
  email:            rajeshrram@outlook.com
  linkedin:         rajeshrram
 

# Custom vars
version:             2.1.0

github:
  repo:           https://github.com/rajeshrram/rajeshrram.github.io